# Generated by Django 3.2.7 on 2021-10-22 09:50

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('uid', models.IntegerField()),
                ('email', models.EmailField(max_length=54)),
                ('gender', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'info',
            },
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
